modLoader="javafml" 
loaderVersion="[28,)"
issueTrackerURL="https://github.com/zeroneye/powah/issues"

[[mods]]
modId="powah"
version="${file.jarVersion}"
textFormatting="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="zeroneye"
description='''
Powah!!.
'''

#[[dependencies.powah]]
#    modId="lollipop"
#    mandatory=true
#    versionRange="[0.0.4,)"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.80,)"
    ordering="NONE"
    side="BOTH"